### PR TITLE
Makes zips iterable

### PR DESCRIPTION
**Pull request by geoghegan**
Imports itertools to do it

### CODE REVIEW

**Comment by racktear** [comment]
Hi @geoghegan, and thanks for the contribution.

Is it required to support a newer python or to handle an edge case?

**Comment by geoghegan** [comment]
Hi @racktear !

I'm not too sure - I'm using Python 2.7.13 on OSX. Without this change, Python errors out complaining that Zips isn't iterable.

**Comment by racktear** [comment]
@geoghegan I understand why this code may fix your problem. But it's better if we dig to the root cause. Could you please print the contents of:

```python
obsoletename
obsoleteversion
obsoleteflags
```

When the error occurs?

**Comment by racktear** [comment]
@geoghegan this PR is now part of another PR by @nicolaasuni. I'll likely merge it, but I still would like to ask for an example of where it breaks. Could you please provide it?

**Comment by racktear** [comment]
I've looked into this problem, and it seems that rpm tools sometime behave inconsistently when writing  obsoleteflags. They write just an integer there instead of a list with one integer.

Here's how it should be fixed:

```python
    if not isinstance(obsoleteflags, list):
        obsoleteflags = [obsoleteflags]
```

**Pull request merged**
